import {
    PUBLICATION_TYPE_AUDIO_DOCUMENT,
    PUBLICATION_TYPE_BOOK,
    PUBLICATION_TYPE_BOOK_CHAPTER,
    PUBLICATION_TYPE_CREATIVE_WORK,
    PUBLICATION_TYPE_DESIGN,
    PUBLICATION_TYPE_IMAGE,
    PUBLICATION_TYPE_JOURNAL_ARTICLE,
    PUBLICATION_TYPE_MANUSCRIPT,
    PUBLICATION_TYPE_RESEARCH_REPORT,
} from 'config/general';

export const publicationTypeHasAdvisoryStatement = record => {
    const publicationTypesWithAdvisoryStatement = [
        PUBLICATION_TYPE_AUDIO_DOCUMENT,
        PUBLICATION_TYPE_BOOK_CHAPTER,
        PUBLICATION_TYPE_BOOK,
        PUBLICATION_TYPE_DESIGN,
        PUBLICATION_TYPE_CREATIVE_WORK,
        PUBLICATION_TYPE_RESEARCH_REPORT,
        PUBLICATION_TYPE_JOURNAL_ARTICLE,
        PUBLICATION_TYPE_IMAGE,
        PUBLICATION_TYPE_MANUSCRIPT,
    ];
    return publicationTypesWithAdvisoryStatement.includes(record.rek_display_type);
};
