version: 0.2

env:
  parameter-store:
    GITHUB_URL: "/CodeBuild/fez-frontend/GITHUB_URL"
    PT_PROJECT: "/CodeBuild/fez-frontend/PT_PROJECT"
    PT_TOKEN: "/CodeBuild/fez-frontend/PT_TOKEN"
    GOOGLE_MAPS_API_KEY: "/CodeBuild/fez-frontend/GOOGLE_MAPS_API_KEY"
    SENTRY_AUTH_TOKEN: "/CodeBuild/fez-frontend/SENTRY_AUTH_TOKEN"
    SENTRY_ORG: "/CodeBuild/fez-frontend/SENTRY_ORG"
    SENTRY_PROJECT: "/CodeBuild/fez-frontend/SENTRY_PROJECT"
phases:
  install:
    runtime-versions:
      java: corretto17
      nodejs: 20
    commands:
      - n 20
  pre_build:
    commands:
      sysctl fs.inotify.max_user_watches &&
      sysctl fs.inotify.max_user_watches=524288 &&
      sysctl fs.inotify.max_user_watches &&
      chmod a+x -R bin/* scripts/*.sh &&
      bin/codebuild-git-wrapper.sh $GITHUB_URL $CI_BRANCH &&
      bin/codebuild-setup.sh
  build:
    commands:
      set &&
      bin/codebuild-test.sh
  #post_build:
    #commands:
      # - command
      # - command
reports:
  coverage-report:
    files:
      - 'coverage/cobertura-coverage.xml'
    file-format: 'COBERTURAXML'
artifacts:
  files:
    - 'coverage/**/*'
    - 'playwright/.results/**/trace.zip'
  name: builds/$CODEBUILD_BUILD_NUMBER/coverage
#cache:
  #paths:
    # - paths
