export const PUBLICATION_SUBTYPES_LOADING = 'PUBLICATION_SUBTYPES_LOADING';
export const PUBLICATION_SUBTYPES_LOADED = 'PUBLICATION_SUBTYPES_LOADED';
export const PUBLICATION_SUBTYPES_LOAD_FAILED = 'PUBLICATION_SUBTYPES_LOAD_FAILED';
