import { getInitialFormValues } from './helpers';
import { journalDoaj } from 'mock/data';

const expected = {
    initialValues: {
        adminSection: {
            abbreviatedTitle: 'ADV NONLINEAR STUD',
            advisoryStatement: {
                htmlText: 'This is an advisory statement',
                plainText: 'This is an advisory statement',
            },
            description:
                'Emphasizes the investigation of language from extralinguistic perspectives in a broad sense, reflecting interest in language among scholars in a variety of fields.',
            jnl_publisher: 'Walter de Gruyter GmbH',
            jnl_title: 'Advanced Nonlinear Studies',
            publicationFormats: 'Print',
            publicationFrequency: 'Bi-monthly',
            publicationYear: '1968',
            refereed: '1',
        },
        bibliographicSection: {
            issns: [
                {
                    rek_order: 2,
                    rek_value: {
                        hasPreload: true,
                        key: '0388-0001',
                        value: {
                            fez_sherpa_romeo: {
                                srm_date_updated: '2021-08-30 06:19:20',
                                srm_id: 33264,
                                srm_issn: '0388-0001',
                                srm_journal_link: 'https://v2.sherpa.ac.uk/id/publication/16950',
                                srm_journal_name: 'Language Sciences',
                                srm_max_embargo_amount: 24,
                                srm_max_embargo_units: 'months',
                                srm_open_access: true,
                                srm_source_id: '16950',
                            },
                            fez_ulrichs: {
                                fez_ulrichscol: null,
                                ulr_abbrev_title: null,
                                ulr_country: 'United Kingdom',
                                ulr_description:
                                    'Emphasizes the investigation of language from extralinguistic perspectives in a broad sense, reflecting interest in language among scholars in a variety of fields.',
                                ulr_formats: 'Print',
                                ulr_frequency: 'Bi-monthly',
                                ulr_id: 27376,
                                ulr_issn: '0388-0001',
                                ulr_last_updated: '2023-11-30 09:20:25',
                                ulr_open_access: '0',
                                ulr_open_access_url: null,
                                ulr_publisher: 'Elsevier Ltd',
                                ulr_refereed: '1',
                                ulr_reviewed: '0',
                                ulr_source_id: '129625',
                                ulr_start_year: '1968',
                                ulr_status: 'Active',
                                ulr_title: 'Language Sciences',
                                ulr_title_id: '89641',
                            },
                        },
                    },
                },
                {
                    rek_order: 1,
                    rek_value: {
                        hasPreload: true,
                        key: '2169-0375',
                        value: {
                            fez_sherpa_romeo: {
                                srm_date_updated: '2022-10-02 16:23:00',
                                srm_id: 20018198,
                                srm_issn: '2169-0375',
                                srm_journal_link: 'https://v2.sherpa.ac.uk/id/publication/36373',
                                srm_journal_name: 'Advanced Nonlinear Studies',
                                srm_max_embargo_amount: null,
                                srm_max_embargo_units: null,
                                srm_open_access: true,
                                srm_source_id: '36373',
                            },
                            fez_ulrichs: {
                                fez_ulrichscol: null,
                                ulr_abbrev_title: null,
                                ulr_country: 'Germany',
                                ulr_description:
                                    'Publishes papers on nonlinear problems, particularly those involving differential equations, dynamical systems and related areas.',
                                ulr_formats: 'Online',
                                ulr_frequency: 'Quarterly',
                                ulr_id: 8089530,
                                ulr_issn: '2169-0375',
                                ulr_last_updated: '2023-12-01 01:53:30',
                                ulr_open_access: '1',
                                ulr_open_access_url: 'https://www.degruyter.com/journal/key/ans/html',
                                ulr_publisher: 'Walter de Gruyter GmbH',
                                ulr_refereed: '1',
                                ulr_reviewed: '0',
                                ulr_source_id: '471881',
                                ulr_start_year: '2009',
                                ulr_status: 'Active',
                                ulr_title: 'Advanced Nonlinear Studies (Online)',
                                ulr_title_id: '473255',
                            },
                        },
                    },
                },
            ],
        },
        doajSection: {
            jnl_doaj_apc_average_price: '1000',
            jnl_doaj_apc_currency: 'EUR',
            jnl_doaj_by: true,
            jnl_doaj_has_doi: true,
            jnl_doaj_homepage_url: 'https://www.degruyter.com/journal/key/ans/html',
            jnl_doaj_issn: '2169-0375',
            jnl_doaj_last_updated: '2022-08-22 09:57:12',
            jnl_doaj_nc: true,
            jnl_doaj_nd: true,
            jnl_doaj_sa: false,
            jnl_doaj_seal: false,
            jnl_doaj_source_id: '340ee43c4c9d4b73ad3f24bb26d98c37',
            jnl_doaj_title: 'Advanced Nonlinear Studies',
            openAccess: false,
        },
        id: 12,
        indexedSection: {
            ahci: {},
            esci: {},
            esi: [
                {
                    jnl_esi_issn: '2169-0375',
                    jnl_esi_source_date: '2023-01-01',
                    jnl_esi_subject: 456440,
                    jnl_esi_subject_lookup: 'Mathematics',
                    jnl_esi_title: 'ADVANCED NONLINEAR STUDIES',
                },
            ],
            pubmed: false,
            scie: {
                fez_journal_cwts: {
                    jnl_cwts_source_year: 2023,
                    jnl_cwts_title: 'ADVANCED NONLINEAR STUDIES',
                },
                jnl_wos_category: '456599|456598',
                jnl_wos_category_index: 'SCIE',
                jnl_wos_category_issn: '2169-0375',
                jnl_wos_category_lookup: 'Mathematics, Applied | Mathematics',
                jnl_wos_category_source_date: '2023-01-01',
                jnl_wos_category_title: 'ADVANCED NONLINEAR STUDIES',
            },
            scopus: true,
            ssci: {},
        },
        journal: {
            fez_journal_abdc: null,
            fez_journal_cite_score: {
                fez_journal_cite_score_asjc_code: [
                    {
                        jnl_cite_score_asjc_code: 453252,
                        jnl_cite_score_asjc_code_id: 155774,
                        jnl_cite_score_asjc_code_lookup: '2600 Mathematics',
                        jnl_cite_score_asjc_code_order: 1,
                        jnl_cite_score_asjc_code_percentile: 81,
                        jnl_cite_score_asjc_code_quartile: 1,
                        jnl_cite_score_asjc_code_rank: 72,
                        jnl_cite_score_asjc_code_rank_out_of: 387,
                        jnl_cite_score_asjc_code_top_10_percent: false,
                    },
                    {
                        jnl_cite_score_asjc_code: 453513,
                        jnl_cite_score_asjc_code_id: 155774,
                        jnl_cite_score_asjc_code_lookup: '3109 Statistical and Nonlinear Physics',
                        jnl_cite_score_asjc_code_order: 2,
                        jnl_cite_score_asjc_code_percentile: 48,
                        jnl_cite_score_asjc_code_quartile: 3,
                        jnl_cite_score_asjc_code_rank: 30,
                        jnl_cite_score_asjc_code_rank_out_of: 57,
                        jnl_cite_score_asjc_code_top_10_percent: false,
                    },
                ],
                jnl_cite_score: '2.6',
                jnl_cite_score_id: 155774,
                jnl_cite_score_issn: '2169-0375',
                jnl_cite_score_percent_cited: '61',
                jnl_cite_score_publisher: 'Walter de Gruyter',
                jnl_cite_score_sjr: '1.67',
                jnl_cite_score_snip: '1.25',
                jnl_cite_score_source_id: '75561',
                jnl_cite_score_source_year: 2022,
                jnl_cite_score_title: 'Advanced Nonlinear Studies',
            },
            fez_journal_doaj: {
                jnl_doaj_apc_average_price: '1000',
                jnl_doaj_apc_currency: 'EUR',
                jnl_doaj_by: true,
                jnl_doaj_has_doi: true,
                jnl_doaj_homepage_url: 'https://www.degruyter.com/journal/key/ans/html',
                jnl_doaj_issn: '2169-0375',
                jnl_doaj_last_updated: '2022-08-22 09:57:12',
                jnl_doaj_nc: true,
                jnl_doaj_nd: true,
                jnl_doaj_sa: false,
                jnl_doaj_seal: false,
                jnl_doaj_source_id: '340ee43c4c9d4b73ad3f24bb26d98c37',
                jnl_doaj_title: 'Advanced Nonlinear Studies',
            },
            fez_journal_era: [
                {
                    fez_journal_era_for_code: [
                        {
                            jnl_era_for_code: '456131',
                            jnl_era_for_code_id: 92195,
                            jnl_era_for_code_lookup: '4901 Applied mathematics',
                            jnl_era_for_code_order: 1,
                        },
                        {
                            jnl_era_for_code: '456156',
                            jnl_era_for_code_id: 92195,
                            jnl_era_for_code_lookup: '4904 Pure mathematics',
                            jnl_era_for_code_order: 2,
                        },
                        {
                            jnl_era_for_code: '456170',
                            jnl_era_for_code_id: 92195,
                            jnl_era_for_code_lookup: '4905 Statistics',
                            jnl_era_for_code_order: 3,
                        },
                    ],
                    jnl_era_id: 92195,
                    jnl_era_source_id: '13',
                    jnl_era_source_year: 2023,
                    jnl_era_title: 'Advanced Nonlinear Studies',
                },
                {
                    fez_journal_era_for_code: [
                        {
                            jnl_era_for_code: '451800',
                            jnl_era_for_code_id: 12,
                            jnl_era_for_code_lookup: '0101 Pure Mathematics',
                            jnl_era_for_code_order: 1,
                        },
                    ],
                    jnl_era_id: 12,
                    jnl_era_source_id: '13',
                    jnl_era_source_year: 2018,
                    jnl_era_title: 'Advanced Nonlinear Studies',
                },
                {
                    fez_journal_era_for_code: [
                        {
                            jnl_era_for_code: '451800',
                            jnl_era_for_code_id: 28407,
                            jnl_era_for_code_lookup: '0101 Pure Mathematics',
                            jnl_era_for_code_order: 1,
                        },
                    ],
                    jnl_era_id: 28407,
                    jnl_era_source_id: '13',
                    jnl_era_source_year: 2015,
                    jnl_era_title: 'Advanced Nonlinear Studies',
                },
                {
                    fez_journal_era_for_code: [
                        {
                            jnl_era_for_code: '451800',
                            jnl_era_for_code_id: 49057,
                            jnl_era_for_code_lookup: '0101 Pure Mathematics',
                            jnl_era_for_code_order: 1,
                        },
                    ],
                    jnl_era_id: 49057,
                    jnl_era_source_id: '13',
                    jnl_era_source_year: 2012,
                    jnl_era_title: 'Advanced Nonlinear Studies',
                },
                {
                    fez_journal_era_for_code: [
                        {
                            jnl_era_for_code: '451800',
                            jnl_era_for_code_id: 73271,
                            jnl_era_for_code_lookup: '0101 Pure Mathematics',
                            jnl_era_for_code_order: 1,
                        },
                    ],
                    jnl_era_id: 73271,
                    jnl_era_source_id: '13',
                    jnl_era_source_year: 2010,
                    jnl_era_title: 'Advanced Nonlinear Studies',
                },
            ],
            fez_journal_esi: [
                {
                    jnl_esi_issn: '2169-0375',
                    jnl_esi_source_date: '2023-01-01',
                    jnl_esi_subject: 456440,
                    jnl_esi_subject_lookup: 'Mathematics',
                    jnl_esi_title: 'ADVANCED NONLINEAR STUDIES',
                },
            ],
            fez_journal_historical_issn: [
                {
                    jnl_historical_issn: '1536-1365',
                    jnl_historical_issn_jid: 12,
                    jnl_historical_issn_order: 1,
                    jnl_historical_issn_type: null,
                },
            ],
            fez_journal_jcr_scie: {
                fez_journal_jcr_scie_category: [
                    {
                        jnl_jcr_scie_category_code: 'PN',
                        jnl_jcr_scie_category_description: 456599,
                        jnl_jcr_scie_category_description_lookup: 'Mathematics, Applied',
                        jnl_jcr_scie_category_id: 63850,
                        jnl_jcr_scie_category_jif_percentile: '67.60',
                        jnl_jcr_scie_category_order: 1,
                        jnl_jcr_scie_category_quartile: 'Q2',
                        jnl_jcr_scie_category_ranking: '87/267',
                    },
                    {
                        jnl_jcr_scie_category_code: 'PQ',
                        jnl_jcr_scie_category_description: 456598,
                        jnl_jcr_scie_category_description_lookup: 'Mathematics',
                        jnl_jcr_scie_category_id: 63850,
                        jnl_jcr_scie_category_jif_percentile: '87.10',
                        jnl_jcr_scie_category_order: 2,
                        jnl_jcr_scie_category_quartile: 'Q1',
                        jnl_jcr_scie_category_ranking: '43/329',
                    },
                ],
                jnl_jcr_scie_5yr_impact_factor: '1.8',
                jnl_jcr_scie_abbrev_title: 'ADV NONLINEAR STUD',
                jnl_jcr_scie_id: 63850,
                jnl_jcr_scie_impact_factor: '1.80',
                jnl_jcr_scie_issn: '2169-0375',
                jnl_jcr_scie_source_year: 2022,
                jnl_jcr_scie_start_year: null,
                jnl_jcr_scie_title: 'ADVANCED NONLINEAR STUDIES',
            },
            fez_journal_jcr_ssci: null,
            fez_journal_nature_index: null,
            fez_journal_pubmed: null,
            fez_journal_read_and_publish: {
                jnl_read_and_publish_is_capped: false,
                jnl_read_and_publish_is_discounted: true,
                jnl_read_and_publish_issn: '2169-0375',
                jnl_read_and_publish_publisher: 'De Gruyter',
                jnl_read_and_publish_source_date: '2023-07-19',
                jnl_read_and_publish_title: 'Advanced Nonlinear Studies',
            },
            fez_journal_wos_category: [
                {
                    fez_journal_cwts: {
                        jnl_cwts_source_year: 2023,
                        jnl_cwts_title: 'ADVANCED NONLINEAR STUDIES',
                    },
                    jnl_wos_category: '456599|456598',
                    jnl_wos_category_index: 'SCIE',
                    jnl_wos_category_issn: '2169-0375',
                    jnl_wos_category_lookup: 'Mathematics, Applied | Mathematics',
                    jnl_wos_category_source_date: '2023-01-01',
                    jnl_wos_category_title: 'ADVANCED NONLINEAR STUDIES',
                },
            ],
            is_favourite: false,
            jnl_advisory_statement: 'This is an advisory statement',
            jnl_created_date: '2021-02-22 00:56:49',
            jnl_editing_start_date: '2023-12-07 23:57:35',
            jnl_editing_user: 'uqlsibba',
            jnl_jid: 12,
            jnl_publisher: 'Walter de Gruyter GmbH',
            jnl_source_id_era: '13',
            jnl_title: 'Advanced Nonlinear Studies',
            jnl_updated_date: '2022-09-08 04:56:28',
            uq_author_id_count: 0,
        },
        uqDataSection: {
            authors: {
                count: 0,
                id: 12,
            },
            jnl_read_and_publish_is_capped: false,
            jnl_read_and_publish_is_discounted: true,
            jnl_read_and_publish_issn: '2169-0375',
            jnl_read_and_publish_publisher: 'De Gruyter',
            jnl_read_and_publish_source_date: '2023-07-19',
            jnl_read_and_publish_title: 'Advanced Nonlinear Studies',
        },
    },
};

describe('Helpers - getInitialFormValues', () => {
    it('expected typical output', () => {
        // typical expectation
        expect(getInitialFormValues(journalDoaj.data)).toEqual(expected);
    });
});
