#!/bin/bash

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".jsx\{0,1\}$")
ESLINT="$(git rev-parse --show-toplevel)/node_modules/.bin/eslint"

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

PASS=true

printf "\n\e[32mRunning ESLint...\e[0m\n\n"

# Check for eslint
if [[ ! -x "$ESLINT" ]]; then
  echo "Please install ESlint (npm i --save-dev eslint)"
  exit 1
fi

for FILE in $STAGED_FILES
do
  "$ESLINT" --config "$(git rev-parse --show-toplevel)/.eslintrc" "$FILE" --quiet

  if [[ "$?" == 0 ]]; then
    printf "\e[92mESLint Passed: $FILE\e[0m\n"
  else
    printf "\e[31mESLint Failed: $FILE\e[0m\n"
    PASS=false
  fi
done

printf "\nESLint validation complete.\n"

if ! $PASS; then
  printf "\n\e[31m\e[1mCOMMIT FAILED.\e[0m \e[31mYour commit contains files that should pass ESLint but do not.\e[0m"
  printf "\n\e[31mPlease fix the ESLint errors and try again.\e[0m\n"
  exit 1
else
  printf "\n\e[92mNo issues found. Proceeding with commit...\e[0m\n\n"
fi
