#!/bin/bash

echo "Pre-commit hook running..."

# Commits should be made directly on Staging branch.
# (Do work in feature branch and then merge into Staging branch)

FORBIDDEN_BRANCH="staging"
THIS_BRANCH=$(git rev-parse --abbrev-ref HEAD)

if [[ "$THIS_BRANCH" == "$FORBIDDEN_BRANCH" ]] ; then
  if [ ! -e ".git/MERGE_MODE" ]; then
    echo "You are trying to commit directly on the $FORBIDDEN_BRANCH branch."
    echo "Please commit in a feature branch and then merge into $FORBIDDEN_BRANCH branch instead."
    echo "Aborting commit."
    exit 1
  fi
fi

# Run code style checks on staged files

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".jsx\{0,1\}$")
FORMATTER="$(git rev-parse --show-toplevel)/node_modules/.bin/prettier-eslint"

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

PASS=true

# Enable nvm if available
if [ -f ~/.nvm/nvm.sh ]; then
  source ~/.nvm/nvm.sh
fi

printf "\n\e[32mRunning Code style checks...\e[0m\n\n"

# Check for prettier-eslint
if [[ ! -x "$FORMATTER" ]]; then
  echo "Please install dependencies by running 'npm install'"
  exit 1
fi

FILE_COUNT=$(echo "$STAGED_FILES" | wc -l)
SECONDS=0

echo "$FILE_COUNT staged file(s) need to be checked for code styles."

if [[ $FILE_COUNT > 30 ]]; then
  printf "Large number of changes detected. Checking all files instead.\n\n\e[31m"
  "$FORMATTER" '**/*.js' --list-different -l silent
  if [[ "$?" != 0 ]]; then
    PASS=false
    printf "\nFile(s) above failed code style checks!"
  else
    printf "\033[2A"
  fi
  printf "\e[0m\n"
else
  for FILE in $STAGED_FILES
  do
    "$FORMATTER" "$FILE" --list-different -l silent > /dev/null

    if [[ "$?" == 0 ]]; then
      printf "\e[92mPass: $FILE\e[0m\n"
    else
      printf "\e[31mFail: $FILE\e[0m\n"
      PASS=false
    fi
  done
fi

printf "\nCode style checks completed in $SECONDS seconds.\n"

if ! $PASS; then
  printf "\n\e[31m\e[1mCOMMIT REJECTED.\e[0m \e[31mYour commit contains files that should pass code style checks but do not.\e[0m\n"
  printf "\nPlease fix code styles and try again. Running '\e[1mnpm run codestyles:fix:staged\e[0m' is a good start."
  printf "\nYou can run '\e[1mnpm run eslint\e[0m' to view ESLint code quality issues, if any.\n\n"
  exit 1
fi

# printf "\n\e[32mRunning Jest...\e[0m\n"

# npm test -- --ci --findRelatedTests $STAGED_FILES

# if [[ "$?" != 0 ]]; then
#   printf "\e[31mEither Jest tests failed, or code coverage is not complete. Please fix and try again.\e[0m\n"
#   exit 2
# else

printf "\n\e[92mNo issues found. Good job!\e[0m\n"
echo "Proceeding with commit..."

# fi