name: GitHub CI

on:
  push:
    branches:
      - feature-example

    paths-ignore:
      - '**.md'
      - '.idea/**'
      - '.vscode/**'

jobs:
  unit-n-codestyles:
    runs-on: ubuntu-18.04
    name: Unit and code style checks

    strategy:
      matrix:
        pipe: [1, 2]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node v11.10.1
        uses: actions/setup-node@v1
        with:
          node-version: 11.10.1

      - name: Get latest version of npm
        run: npm i -g npm@6

      - name: Install dependencies
        run: npm ci

      - name: Jest tests
        run: npm run test:unit:ci${{ matrix.pipe }}
        env:
          TZ: 'Australia/Brisbane'

      - name: Upload code coverage
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage/jest/coverage-final.json

      - name: Code style checks
        run: if [[ ${{ matrix.pipe }} == 1 ]]; then npm run codestyles:files -s; fi
